export const ALERTS = {
  GENERIC_ERROR: 'Something went wrong. Please try again.',
  NETWORK_ERROR: 'Network error. Please check your connection.',
  OFFLINE_ACTION: 'This action is unavailable while offline.',
  CREATE_SUCCESS: 'Ticket created successfully.',
  CREATE_FAILED: 'Failed to create ticket.',
  UPDATE_SUCCESS: 'Ticket updated successfully.',
  UPDATE_FAILED: 'Failed to update ticket.',
  REPLY_SUCCESS: 'Reply sent successfully.',
  REPLY_FAILED: 'Failed to send reply.',
  NOTE_SUCCESS: 'Internal note added.',
  NOTE_FAILED: 'Failed to add internal note.',
  ASSIGN_SUCCESS: 'Ticket assignment updated.',
  ASSIGN_FAILED: 'Failed to update assignment.',
  REASSIGN_RESOLVED: 'Resolved tickets cannot be reassigned.',
  VALIDATION: {
    REQUIRED: 'This field is required.',
    EMAIL_INVALID: 'Please enter a valid email address.',
    NAME_INVALID: 'Name can contain letters and spaces only.',
    NAME_MAX: 'Name must be 50 characters or less.',
    SUBJECT_MAX: 'Subject must be 100 characters or less.',
    DESCRIPTION_MAX: 'Description must be 1000 characters or less.',
    REPLY_REQUIRED: 'Reply cannot be empty.',
    NOTE_REQUIRED: 'Note cannot be empty.',
  },
};
