export const TITLES = {
  DASHBOARD: {
    TITLE: 'Support Dashboard',
    OPEN_TICKETS: 'Total Open Tickets',
    ASSIGNED_TO_ME: 'Tickets Assigned To Me',
    RESOLVED_TODAY: 'Resolved Today',
    HIGH_PRIORITY: 'High Priority Tickets',
    VIEW_ALL: 'View All Tickets',
    CREATE_TICKET: 'Create Ticket',
  },
  TICKET_LIST: {
    TITLE: 'Tickets',
    SEARCH_PLACEHOLDER: 'Search by customer or subject',
    SORT_NEWEST: 'Newest First',
    SORT_OLDEST: 'Oldest First',
    EMPTY: 'No tickets yet',
    EMPTY_CTA: 'Create your first ticket',
    NO_RESULTS: 'No results for',
    NO_MORE: 'No more tickets',
    LOADING: 'Loading tickets...',
  },
  TICKET_DETAILS: {
    TITLE: 'Ticket Details',
    CUSTOMER_DETAILS: 'Customer Details',
    CONVERSATION: 'Conversation',
    TIMELINE: 'Activity Timeline',
    ATTACHMENTS: 'Attachments',
    REPLY: 'Reply to Customer',
    INTERNAL_NOTE: 'Add Internal Note',
    CHANGE_STATUS: 'Change Status',
    CHANGE_PRIORITY: 'Change Priority',
    ASSIGNMENT: 'Assignment',
    ASSIGN_SELF: 'Assign to Me',
    ASSIGN_OTHER: 'Assign to Agent',
    UNASSIGN: 'Unassign',
    RETRY_REPLY: 'Retry Send',
    NO_ATTACHMENTS: 'No attachments',
    NO_CONVERSATION: 'No conversation yet',
    NO_TIMELINE: 'No activity yet',
    TICKET_CHANGED: 'Ticket was updated. Refreshed.',
  },
  CREATE_TICKET: {
    TITLE: 'Create Ticket',
    CUSTOMER_NAME: 'Customer Name',
    EMAIL: 'Email',
    SUBJECT: 'Subject',
    DESCRIPTION: 'Description',
    PRIORITY: 'Priority',
    SUBMIT: 'Create Ticket',
  },
  FILTERS: {
    STATUS_ALL: 'All Status',
    STATUS_OPEN: 'Open',
    STATUS_IN_PROGRESS: 'In Progress',
    STATUS_RESOLVED: 'Resolved',
    PRIORITY_ALL: 'All Priority',
    PRIORITY_LOW: 'Low',
    PRIORITY_MEDIUM: 'Medium',
    PRIORITY_HIGH: 'High',
  },
  LABELS: {
    TICKET_ID: 'Ticket ID',
    CUSTOMER_NAME: 'Customer',
    SUBJECT: 'Subject',
    STATUS: 'Status',
    PRIORITY: 'Priority',
    CREATED: 'Created',
    EMAIL: 'Email',
    ASSIGNED_TO: 'Assigned To',
    UNASSIGNED: 'Unassigned',
    RETRY: 'Retry',
    OFFLINE: 'You are offline. Some actions are disabled.',
  },
  STATUS: {
    OPEN: 'Open',
    IN_PROGRESS: 'In Progress',
    RESOLVED: 'Resolved',
  },
  PRIORITY: {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
  },
  TIMELINE: {
    CREATED: 'Ticket created',
    STATUS_CHANGED: 'Status changed',
    PRIORITY_CHANGED: 'Priority changed',
    ASSIGNED: 'Assignment changed',
    COMMENT_ADDED: 'Comment added',
  },
};
